development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: business_tracker_backend_production
#  { "redis://localhost:6379/1" }